x,y=input("enter numbers to do operations:").split()
a=int(x)+int(y)
b=int(x)-int(y)
c=int(x)*int(y)
d=int(x)/int(y)
print("addition of "+x+" and "+y+" =",a)
print("Substraction of "+x+" and "+y+" =",b)
print("Multiplication of "+x+" and "+y+" =",c)
print("Percetile of "+x+" and "+y+" =",d)
print("Square of "+x+" is :",int(x)**int(y))
